//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_htc_viu : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean viu_press_00
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_press_00;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_press_01
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_press_01;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_press_02
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_press_02;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_press_03
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_press_03;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_press_04
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_press_04;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_press_05
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_press_05;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_press_06
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_press_06;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_press_07
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_press_07;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_press_31
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_press_31;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_press_32
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_press_32;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_press_33
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_press_33;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_press_34
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_press_34;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_press_35
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_press_35;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_touch_00
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_touch_00;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_touch_01
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_touch_01;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_touch_02
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_touch_02;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_touch_03
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_touch_03;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_touch_04
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_touch_04;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_touch_05
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_touch_05;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_touch_06
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_touch_06;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_touch_07
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_touch_07;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_touch_31
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_touch_31;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_touch_32
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_touch_32;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_touch_33
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_touch_33;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_touch_34
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_touch_34;
            }
        }
        
        public virtual SteamVR_Action_Boolean viu_touch_35
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_touch_35;
            }
        }
        
        public virtual SteamVR_Action_Single viu_axis_0x
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_0x;
            }
        }
        
        public virtual SteamVR_Action_Single viu_axis_0y
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_0y;
            }
        }
        
        public virtual SteamVR_Action_Single viu_axis_1x
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_1x;
            }
        }
        
        public virtual SteamVR_Action_Single viu_axis_1y
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_1y;
            }
        }
        
        public virtual SteamVR_Action_Single viu_axis_2x
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_2x;
            }
        }
        
        public virtual SteamVR_Action_Single viu_axis_2y
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_2y;
            }
        }
        
        public virtual SteamVR_Action_Single viu_axis_3x
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_3x;
            }
        }
        
        public virtual SteamVR_Action_Single viu_axis_3y
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_3y;
            }
        }
        
        public virtual SteamVR_Action_Single viu_axis_4x
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_4x;
            }
        }
        
        public virtual SteamVR_Action_Single viu_axis_4y
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_4y;
            }
        }
        
        public virtual SteamVR_Action_Vector2 viu_axis_0xy
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_0xy;
            }
        }
        
        public virtual SteamVR_Action_Vector2 viu_axis_1xy
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_1xy;
            }
        }
        
        public virtual SteamVR_Action_Vector2 viu_axis_2xy
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_2xy;
            }
        }
        
        public virtual SteamVR_Action_Vector2 viu_axis_3xy
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_3xy;
            }
        }
        
        public virtual SteamVR_Action_Vector2 viu_axis_4xy
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_axis_4xy;
            }
        }
        
        public virtual SteamVR_Action_Vibration viu_vib_01
        {
            get
            {
                return SteamVR_Actions.htc_viu_viu_vib_01;
            }
        }
    }
}
