//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_InteractUI;
        
        private static SteamVR_Action_Boolean p_default_Teleport;
        
        private static SteamVR_Action_Boolean p_default_GrabPinch;
        
        private static SteamVR_Action_Boolean p_default_GrabGrip;
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonRightHand;
        
        private static SteamVR_Action_Single p_default_Squeeze;
        
        private static SteamVR_Action_Boolean p_default_HeadsetOnHead;
        
        private static SteamVR_Action_Boolean p_default_SnapTurnLeft;
        
        private static SteamVR_Action_Boolean p_default_SnapTurnRight;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        private static SteamVR_Action_Vector2 p_platformer_Move;
        
        private static SteamVR_Action_Boolean p_platformer_Jump;
        
        private static SteamVR_Action_Vector2 p_buggy_Steering;
        
        private static SteamVR_Action_Single p_buggy_Throttle;
        
        private static SteamVR_Action_Boolean p_buggy_Brake;
        
        private static SteamVR_Action_Boolean p_buggy_Reset;
        
        private static SteamVR_Action_Pose p_mixedreality_ExternalCamera;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_press_00;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_press_01;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_press_02;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_press_03;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_press_04;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_press_05;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_press_06;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_press_07;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_press_31;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_press_32;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_press_33;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_press_34;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_press_35;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_touch_00;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_touch_01;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_touch_02;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_touch_03;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_touch_04;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_touch_05;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_touch_06;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_touch_07;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_touch_31;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_touch_32;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_touch_33;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_touch_34;
        
        private static SteamVR_Action_Boolean p_htc_viu_viu_touch_35;
        
        private static SteamVR_Action_Single p_htc_viu_viu_axis_0x;
        
        private static SteamVR_Action_Single p_htc_viu_viu_axis_0y;
        
        private static SteamVR_Action_Single p_htc_viu_viu_axis_1x;
        
        private static SteamVR_Action_Single p_htc_viu_viu_axis_1y;
        
        private static SteamVR_Action_Single p_htc_viu_viu_axis_2x;
        
        private static SteamVR_Action_Single p_htc_viu_viu_axis_2y;
        
        private static SteamVR_Action_Single p_htc_viu_viu_axis_3x;
        
        private static SteamVR_Action_Single p_htc_viu_viu_axis_3y;
        
        private static SteamVR_Action_Single p_htc_viu_viu_axis_4x;
        
        private static SteamVR_Action_Single p_htc_viu_viu_axis_4y;
        
        private static SteamVR_Action_Vector2 p_htc_viu_viu_axis_0xy;
        
        private static SteamVR_Action_Vector2 p_htc_viu_viu_axis_1xy;
        
        private static SteamVR_Action_Vector2 p_htc_viu_viu_axis_2xy;
        
        private static SteamVR_Action_Vector2 p_htc_viu_viu_axis_3xy;
        
        private static SteamVR_Action_Vector2 p_htc_viu_viu_axis_4xy;
        
        private static SteamVR_Action_Vibration p_htc_viu_viu_vib_01;
        
        public static SteamVR_Action_Boolean default_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_default_InteractUI.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Teleport
        {
            get
            {
                return SteamVR_Actions.p_default_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_default_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabGrip
        {
            get
            {
                return SteamVR_Actions.p_default_GrabGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Single default_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_default_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_default_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Vector2 platformer_Move
        {
            get
            {
                return SteamVR_Actions.p_platformer_Move.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean platformer_Jump
        {
            get
            {
                return SteamVR_Actions.p_platformer_Jump.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 buggy_Steering
        {
            get
            {
                return SteamVR_Actions.p_buggy_Steering.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single buggy_Throttle
        {
            get
            {
                return SteamVR_Actions.p_buggy_Throttle.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Brake
        {
            get
            {
                return SteamVR_Actions.p_buggy_Brake.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Reset
        {
            get
            {
                return SteamVR_Actions.p_buggy_Reset.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose mixedreality_ExternalCamera
        {
            get
            {
                return SteamVR_Actions.p_mixedreality_ExternalCamera.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_press_00
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_press_00.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_press_01
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_press_01.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_press_02
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_press_02.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_press_03
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_press_03.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_press_04
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_press_04.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_press_05
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_press_05.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_press_06
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_press_06.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_press_07
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_press_07.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_press_31
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_press_31.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_press_32
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_press_32.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_press_33
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_press_33.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_press_34
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_press_34.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_press_35
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_press_35.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_touch_00
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_touch_00.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_touch_01
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_touch_01.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_touch_02
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_touch_02.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_touch_03
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_touch_03.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_touch_04
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_touch_04.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_touch_05
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_touch_05.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_touch_06
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_touch_06.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_touch_07
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_touch_07.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_touch_31
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_touch_31.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_touch_32
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_touch_32.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_touch_33
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_touch_33.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_touch_34
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_touch_34.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean htc_viu_viu_touch_35
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_touch_35.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single htc_viu_viu_axis_0x
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_0x.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single htc_viu_viu_axis_0y
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_0y.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single htc_viu_viu_axis_1x
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_1x.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single htc_viu_viu_axis_1y
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_1y.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single htc_viu_viu_axis_2x
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_2x.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single htc_viu_viu_axis_2y
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_2y.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single htc_viu_viu_axis_3x
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_3x.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single htc_viu_viu_axis_3y
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_3y.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single htc_viu_viu_axis_4x
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_4x.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single htc_viu_viu_axis_4y
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_4y.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Vector2 htc_viu_viu_axis_0xy
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_0xy.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 htc_viu_viu_axis_1xy
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_1xy.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 htc_viu_viu_axis_2xy
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_2xy.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 htc_viu_viu_axis_3xy
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_3xy.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 htc_viu_viu_axis_4xy
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_axis_4xy.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vibration htc_viu_viu_vib_01
        {
            get
            {
                return SteamVR_Actions.p_htc_viu_viu_vib_01.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera,
                    SteamVR_Actions.htc_viu_viu_press_00,
                    SteamVR_Actions.htc_viu_viu_press_01,
                    SteamVR_Actions.htc_viu_viu_press_02,
                    SteamVR_Actions.htc_viu_viu_press_03,
                    SteamVR_Actions.htc_viu_viu_press_04,
                    SteamVR_Actions.htc_viu_viu_press_05,
                    SteamVR_Actions.htc_viu_viu_press_06,
                    SteamVR_Actions.htc_viu_viu_press_07,
                    SteamVR_Actions.htc_viu_viu_press_31,
                    SteamVR_Actions.htc_viu_viu_press_32,
                    SteamVR_Actions.htc_viu_viu_press_33,
                    SteamVR_Actions.htc_viu_viu_press_34,
                    SteamVR_Actions.htc_viu_viu_press_35,
                    SteamVR_Actions.htc_viu_viu_touch_00,
                    SteamVR_Actions.htc_viu_viu_touch_01,
                    SteamVR_Actions.htc_viu_viu_touch_02,
                    SteamVR_Actions.htc_viu_viu_touch_03,
                    SteamVR_Actions.htc_viu_viu_touch_04,
                    SteamVR_Actions.htc_viu_viu_touch_05,
                    SteamVR_Actions.htc_viu_viu_touch_06,
                    SteamVR_Actions.htc_viu_viu_touch_07,
                    SteamVR_Actions.htc_viu_viu_touch_31,
                    SteamVR_Actions.htc_viu_viu_touch_32,
                    SteamVR_Actions.htc_viu_viu_touch_33,
                    SteamVR_Actions.htc_viu_viu_touch_34,
                    SteamVR_Actions.htc_viu_viu_touch_35,
                    SteamVR_Actions.htc_viu_viu_axis_0x,
                    SteamVR_Actions.htc_viu_viu_axis_0y,
                    SteamVR_Actions.htc_viu_viu_axis_1x,
                    SteamVR_Actions.htc_viu_viu_axis_1y,
                    SteamVR_Actions.htc_viu_viu_axis_2x,
                    SteamVR_Actions.htc_viu_viu_axis_2y,
                    SteamVR_Actions.htc_viu_viu_axis_3x,
                    SteamVR_Actions.htc_viu_viu_axis_3y,
                    SteamVR_Actions.htc_viu_viu_axis_4x,
                    SteamVR_Actions.htc_viu_viu_axis_4y,
                    SteamVR_Actions.htc_viu_viu_axis_0xy,
                    SteamVR_Actions.htc_viu_viu_axis_1xy,
                    SteamVR_Actions.htc_viu_viu_axis_2xy,
                    SteamVR_Actions.htc_viu_viu_axis_3xy,
                    SteamVR_Actions.htc_viu_viu_axis_4xy,
                    SteamVR_Actions.htc_viu_viu_vib_01};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera,
                    SteamVR_Actions.htc_viu_viu_press_00,
                    SteamVR_Actions.htc_viu_viu_press_01,
                    SteamVR_Actions.htc_viu_viu_press_02,
                    SteamVR_Actions.htc_viu_viu_press_03,
                    SteamVR_Actions.htc_viu_viu_press_04,
                    SteamVR_Actions.htc_viu_viu_press_05,
                    SteamVR_Actions.htc_viu_viu_press_06,
                    SteamVR_Actions.htc_viu_viu_press_07,
                    SteamVR_Actions.htc_viu_viu_press_31,
                    SteamVR_Actions.htc_viu_viu_press_32,
                    SteamVR_Actions.htc_viu_viu_press_33,
                    SteamVR_Actions.htc_viu_viu_press_34,
                    SteamVR_Actions.htc_viu_viu_press_35,
                    SteamVR_Actions.htc_viu_viu_touch_00,
                    SteamVR_Actions.htc_viu_viu_touch_01,
                    SteamVR_Actions.htc_viu_viu_touch_02,
                    SteamVR_Actions.htc_viu_viu_touch_03,
                    SteamVR_Actions.htc_viu_viu_touch_04,
                    SteamVR_Actions.htc_viu_viu_touch_05,
                    SteamVR_Actions.htc_viu_viu_touch_06,
                    SteamVR_Actions.htc_viu_viu_touch_07,
                    SteamVR_Actions.htc_viu_viu_touch_31,
                    SteamVR_Actions.htc_viu_viu_touch_32,
                    SteamVR_Actions.htc_viu_viu_touch_33,
                    SteamVR_Actions.htc_viu_viu_touch_34,
                    SteamVR_Actions.htc_viu_viu_touch_35,
                    SteamVR_Actions.htc_viu_viu_axis_0x,
                    SteamVR_Actions.htc_viu_viu_axis_0y,
                    SteamVR_Actions.htc_viu_viu_axis_1x,
                    SteamVR_Actions.htc_viu_viu_axis_1y,
                    SteamVR_Actions.htc_viu_viu_axis_2x,
                    SteamVR_Actions.htc_viu_viu_axis_2y,
                    SteamVR_Actions.htc_viu_viu_axis_3x,
                    SteamVR_Actions.htc_viu_viu_axis_3y,
                    SteamVR_Actions.htc_viu_viu_axis_4x,
                    SteamVR_Actions.htc_viu_viu_axis_4y,
                    SteamVR_Actions.htc_viu_viu_axis_0xy,
                    SteamVR_Actions.htc_viu_viu_axis_1xy,
                    SteamVR_Actions.htc_viu_viu_axis_2xy,
                    SteamVR_Actions.htc_viu_viu_axis_3xy,
                    SteamVR_Actions.htc_viu_viu_axis_4xy};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.htc_viu_viu_vib_01};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.htc_viu_viu_vib_01};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.mixedreality_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.htc_viu_viu_press_00,
                    SteamVR_Actions.htc_viu_viu_press_01,
                    SteamVR_Actions.htc_viu_viu_press_02,
                    SteamVR_Actions.htc_viu_viu_press_03,
                    SteamVR_Actions.htc_viu_viu_press_04,
                    SteamVR_Actions.htc_viu_viu_press_05,
                    SteamVR_Actions.htc_viu_viu_press_06,
                    SteamVR_Actions.htc_viu_viu_press_07,
                    SteamVR_Actions.htc_viu_viu_press_31,
                    SteamVR_Actions.htc_viu_viu_press_32,
                    SteamVR_Actions.htc_viu_viu_press_33,
                    SteamVR_Actions.htc_viu_viu_press_34,
                    SteamVR_Actions.htc_viu_viu_press_35,
                    SteamVR_Actions.htc_viu_viu_touch_00,
                    SteamVR_Actions.htc_viu_viu_touch_01,
                    SteamVR_Actions.htc_viu_viu_touch_02,
                    SteamVR_Actions.htc_viu_viu_touch_03,
                    SteamVR_Actions.htc_viu_viu_touch_04,
                    SteamVR_Actions.htc_viu_viu_touch_05,
                    SteamVR_Actions.htc_viu_viu_touch_06,
                    SteamVR_Actions.htc_viu_viu_touch_07,
                    SteamVR_Actions.htc_viu_viu_touch_31,
                    SteamVR_Actions.htc_viu_viu_touch_32,
                    SteamVR_Actions.htc_viu_viu_touch_33,
                    SteamVR_Actions.htc_viu_viu_touch_34,
                    SteamVR_Actions.htc_viu_viu_touch_35};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.htc_viu_viu_axis_0x,
                    SteamVR_Actions.htc_viu_viu_axis_0y,
                    SteamVR_Actions.htc_viu_viu_axis_1x,
                    SteamVR_Actions.htc_viu_viu_axis_1y,
                    SteamVR_Actions.htc_viu_viu_axis_2x,
                    SteamVR_Actions.htc_viu_viu_axis_2y,
                    SteamVR_Actions.htc_viu_viu_axis_3x,
                    SteamVR_Actions.htc_viu_viu_axis_3y,
                    SteamVR_Actions.htc_viu_viu_axis_4x,
                    SteamVR_Actions.htc_viu_viu_axis_4y};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.htc_viu_viu_axis_0xy,
                    SteamVR_Actions.htc_viu_viu_axis_1xy,
                    SteamVR_Actions.htc_viu_viu_axis_2xy,
                    SteamVR_Actions.htc_viu_viu_axis_3xy,
                    SteamVR_Actions.htc_viu_viu_axis_4xy};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.htc_viu_viu_press_00,
                    SteamVR_Actions.htc_viu_viu_press_01,
                    SteamVR_Actions.htc_viu_viu_press_02,
                    SteamVR_Actions.htc_viu_viu_press_03,
                    SteamVR_Actions.htc_viu_viu_press_04,
                    SteamVR_Actions.htc_viu_viu_press_05,
                    SteamVR_Actions.htc_viu_viu_press_06,
                    SteamVR_Actions.htc_viu_viu_press_07,
                    SteamVR_Actions.htc_viu_viu_press_31,
                    SteamVR_Actions.htc_viu_viu_press_32,
                    SteamVR_Actions.htc_viu_viu_press_33,
                    SteamVR_Actions.htc_viu_viu_press_34,
                    SteamVR_Actions.htc_viu_viu_press_35,
                    SteamVR_Actions.htc_viu_viu_touch_00,
                    SteamVR_Actions.htc_viu_viu_touch_01,
                    SteamVR_Actions.htc_viu_viu_touch_02,
                    SteamVR_Actions.htc_viu_viu_touch_03,
                    SteamVR_Actions.htc_viu_viu_touch_04,
                    SteamVR_Actions.htc_viu_viu_touch_05,
                    SteamVR_Actions.htc_viu_viu_touch_06,
                    SteamVR_Actions.htc_viu_viu_touch_07,
                    SteamVR_Actions.htc_viu_viu_touch_31,
                    SteamVR_Actions.htc_viu_viu_touch_32,
                    SteamVR_Actions.htc_viu_viu_touch_33,
                    SteamVR_Actions.htc_viu_viu_touch_34,
                    SteamVR_Actions.htc_viu_viu_touch_35,
                    SteamVR_Actions.htc_viu_viu_axis_0x,
                    SteamVR_Actions.htc_viu_viu_axis_0y,
                    SteamVR_Actions.htc_viu_viu_axis_1x,
                    SteamVR_Actions.htc_viu_viu_axis_1y,
                    SteamVR_Actions.htc_viu_viu_axis_2x,
                    SteamVR_Actions.htc_viu_viu_axis_2y,
                    SteamVR_Actions.htc_viu_viu_axis_3x,
                    SteamVR_Actions.htc_viu_viu_axis_3y,
                    SteamVR_Actions.htc_viu_viu_axis_4x,
                    SteamVR_Actions.htc_viu_viu_axis_4y,
                    SteamVR_Actions.htc_viu_viu_axis_0xy,
                    SteamVR_Actions.htc_viu_viu_axis_1xy,
                    SteamVR_Actions.htc_viu_viu_axis_2xy,
                    SteamVR_Actions.htc_viu_viu_axis_3xy,
                    SteamVR_Actions.htc_viu_viu_axis_4xy};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/InteractUI")));
            SteamVR_Actions.p_default_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Teleport")));
            SteamVR_Actions.p_default_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabPinch")));
            SteamVR_Actions.p_default_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabGrip")));
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/Squeeze")));
            SteamVR_Actions.p_default_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/HeadsetOnHead")));
            SteamVR_Actions.p_default_SnapTurnLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SnapTurnLeft")));
            SteamVR_Actions.p_default_SnapTurnRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SnapTurnRight")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
            SteamVR_Actions.p_platformer_Move = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/platformer/in/Move")));
            SteamVR_Actions.p_platformer_Jump = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/platformer/in/Jump")));
            SteamVR_Actions.p_buggy_Steering = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/buggy/in/Steering")));
            SteamVR_Actions.p_buggy_Throttle = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/buggy/in/Throttle")));
            SteamVR_Actions.p_buggy_Brake = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Brake")));
            SteamVR_Actions.p_buggy_Reset = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Reset")));
            SteamVR_Actions.p_mixedreality_ExternalCamera = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/mixedreality/in/ExternalCamera")));
            SteamVR_Actions.p_htc_viu_viu_press_00 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_press_00")));
            SteamVR_Actions.p_htc_viu_viu_press_01 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_press_01")));
            SteamVR_Actions.p_htc_viu_viu_press_02 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_press_02")));
            SteamVR_Actions.p_htc_viu_viu_press_03 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_press_03")));
            SteamVR_Actions.p_htc_viu_viu_press_04 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_press_04")));
            SteamVR_Actions.p_htc_viu_viu_press_05 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_press_05")));
            SteamVR_Actions.p_htc_viu_viu_press_06 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_press_06")));
            SteamVR_Actions.p_htc_viu_viu_press_07 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_press_07")));
            SteamVR_Actions.p_htc_viu_viu_press_31 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_press_31")));
            SteamVR_Actions.p_htc_viu_viu_press_32 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_press_32")));
            SteamVR_Actions.p_htc_viu_viu_press_33 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_press_33")));
            SteamVR_Actions.p_htc_viu_viu_press_34 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_press_34")));
            SteamVR_Actions.p_htc_viu_viu_press_35 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_press_35")));
            SteamVR_Actions.p_htc_viu_viu_touch_00 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_touch_00")));
            SteamVR_Actions.p_htc_viu_viu_touch_01 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_touch_01")));
            SteamVR_Actions.p_htc_viu_viu_touch_02 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_touch_02")));
            SteamVR_Actions.p_htc_viu_viu_touch_03 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_touch_03")));
            SteamVR_Actions.p_htc_viu_viu_touch_04 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_touch_04")));
            SteamVR_Actions.p_htc_viu_viu_touch_05 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_touch_05")));
            SteamVR_Actions.p_htc_viu_viu_touch_06 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_touch_06")));
            SteamVR_Actions.p_htc_viu_viu_touch_07 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_touch_07")));
            SteamVR_Actions.p_htc_viu_viu_touch_31 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_touch_31")));
            SteamVR_Actions.p_htc_viu_viu_touch_32 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_touch_32")));
            SteamVR_Actions.p_htc_viu_viu_touch_33 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_touch_33")));
            SteamVR_Actions.p_htc_viu_viu_touch_34 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_touch_34")));
            SteamVR_Actions.p_htc_viu_viu_touch_35 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/htc_viu/in/viu_touch_35")));
            SteamVR_Actions.p_htc_viu_viu_axis_0x = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/htc_viu/in/viu_axis_0x")));
            SteamVR_Actions.p_htc_viu_viu_axis_0y = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/htc_viu/in/viu_axis_0y")));
            SteamVR_Actions.p_htc_viu_viu_axis_1x = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/htc_viu/in/viu_axis_1x")));
            SteamVR_Actions.p_htc_viu_viu_axis_1y = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/htc_viu/in/viu_axis_1y")));
            SteamVR_Actions.p_htc_viu_viu_axis_2x = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/htc_viu/in/viu_axis_2x")));
            SteamVR_Actions.p_htc_viu_viu_axis_2y = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/htc_viu/in/viu_axis_2y")));
            SteamVR_Actions.p_htc_viu_viu_axis_3x = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/htc_viu/in/viu_axis_3x")));
            SteamVR_Actions.p_htc_viu_viu_axis_3y = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/htc_viu/in/viu_axis_3y")));
            SteamVR_Actions.p_htc_viu_viu_axis_4x = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/htc_viu/in/viu_axis_4x")));
            SteamVR_Actions.p_htc_viu_viu_axis_4y = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/htc_viu/in/viu_axis_4y")));
            SteamVR_Actions.p_htc_viu_viu_axis_0xy = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/htc_viu/in/viu_axis_0xy")));
            SteamVR_Actions.p_htc_viu_viu_axis_1xy = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/htc_viu/in/viu_axis_1xy")));
            SteamVR_Actions.p_htc_viu_viu_axis_2xy = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/htc_viu/in/viu_axis_2xy")));
            SteamVR_Actions.p_htc_viu_viu_axis_3xy = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/htc_viu/in/viu_axis_3xy")));
            SteamVR_Actions.p_htc_viu_viu_axis_4xy = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/htc_viu/in/viu_axis_4xy")));
            SteamVR_Actions.p_htc_viu_viu_vib_01 = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/htc_viu/out/viu_vib_01")));
        }
    }
}
